parameters:
  - name: stageName
    type: string
  - name: environmentName
    type: string
  - name: appName
    type: string

stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy to the ${{ parameters.environmentName }} environment'
  condition: succeeded()
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-22.04'
    environment: ${{ parameters.environmentName }}
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: ${{ parameters.environmentName }} website'
            inputs:
              azureSubscription: 'Visual Studio Enterprise Subscription(b2d13dde-c5ef-4a3c-b9d4-da08a1753a12)'
              appType: 'webAppLinux'
              appName: ${{ parameters.appName }}
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
